### ISSUE TITLE
Caused by: org.xml.sax.SAXParseException; systemId: file:/E:/opensource/github/java-multithread-downloader/files/test1.tmp; lineNumber: 1; columnNumber: 1; 文件提前结束。

### ISSUE THREAD

**Issue by shuaiqingli** [daimajia/java-multithread-downloader#7]
javax.xml.bind.UnmarshalException
- with linked exception:
  [org.xml.sax.SAXParseException; systemId: file:/E:/opensource/github/java-multithread-downloader/files/test3.tmp; lineNumber: 1; columnNumber: 1; 文件提前结束。]
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162)
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171)
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:189)
  at com.zhan_dui.download.DownloadMission.resumeMission(DownloadMission.java:312)
  at com.zhan_dui.download.DownloadMission.startMission(DownloadMission.java:339)
  at com.zhan_dui.download.DownloadManager.start(DownloadManager.java:64)
  at com.zhan_dui.download.Test.main(Test.java:29)
  Caused by: org.xml.sax.SAXParseException; systemId: file:/E:/opensource/github/java-multithread-downloader/files/test3.tmp; lineNumber: 1; columnNumber: 1; 文件提前结束。
  at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
  at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
  at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
  at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
  at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1438)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
  at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
  at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
  at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
  at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
  ... 9 more
  Download Task ID:18 has been started! Range From 0 To -1
  Download Task ID:19 has been started! Range From 0 To -1
  javax.xml.bind.UnmarshalException
- with linked exception:
  [org.xml.sax.SAXParseException; systemId: file:/E:/opensource/github/java-multithread-downloader/files/test2.tmp; lineNumber: 1; columnNumber: 1; 文件提前结束。]
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162)
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171)
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:189)
  at com.zhan_dui.download.DownloadMission.resumeMission(DownloadMission.java:312)
  at com.zhan_dui.download.DownloadMission.startMission(DownloadMission.java:339)
  at com.zhan_dui.download.DownloadManager.start(DownloadManager.java:64)
  at com.zhan_dui.download.Test.main(Test.java:29)
  Caused by: org.xml.sax.SAXParseException; systemId: file:/E:/opensource/github/java-multithread-downloader/files/test2.tmp; lineNumber: 1; columnNumber: 1; 文件提前结束。
  at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
  at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
  at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
  at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
  at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1438)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
  at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
  at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
  at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
  at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
  ... 9 more
  Download Task ID:20 has been started! Range From 0 To -1
  Download Task ID:17 has been started! Range From 0 To -1
  java.net.ConnectException: Connection timed out: connect
  at java.net.DualStackPlainSocketImpl.connect0(Native Method)
  at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:589)
  at java.net.Socket.connect(Socket.java:538)
  at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
  at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
  at sun.net.www.http.HttpClient.New(HttpClient.java:308)
  at sun.net.www.http.HttpClient.New(HttpClient.java:326)
  at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
  at com.zhan_dui.download.DownloadRunnable.run(DownloadRunnable.java:101)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  18 has been succeesfully finished!
  CurrentPosition:0 EndPosition:-1Rmaining:-1 com.zhan_dui.download.DownloadRunnable@30c479ed can not be splited ,less than 1M
  CurrentPosition:0 EndPosition:-1Rmaining:-1 com.zhan_dui.download.DownloadRunnable@7bd3e136 can not be splited ,less than 1M
  CurrentPosition:0 EndPosition:-1Rmaining:-1 com.zhan_dui.download.DownloadRunnable@4102ce8d can not be splited ,less than 1M
  java.net.ConnectException: Connection timed out: connect
  at java.net.DualStackPlainSocketImpl.connect0(Native Method)
  at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:589)
  at java.net.Socket.connect(Socket.java:538)
  at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
  at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
  at sun.net.www.http.HttpClient.New(HttpClient.java:308)
  at sun.net.www.http.HttpClient.New(HttpClient.java:326)
  at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
  at com.zhan_dui.download.DownloadRunnable.run(DownloadRunnable.java:101)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  20 has been succeesfully finished!
  CurrentPosition:0 EndPosition:-1Rmaining:-1 com.zhan_dui.download.DownloadRunnable@30c479ed can not be splited ,less than 1M
  CurrentPosition:0 EndPosition:-1Rmaining:-1 com.zhan_dui.download.DownloadRunnable@7bd3e136 can not be splited ,less than 1M
  java.net.ConnectException: Connection timed out: connect
  at java.net.DualStackPlainSocketImpl.connect0(Native Method)
  at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:589)
  at java.net.Socket.connect(Socket.java:538)
  at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
  at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
  at sun.net.www.http.HttpClient.New(HttpClient.java:308)
  at sun.net.www.http.HttpClient.New(HttpClient.java:326)
  at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
  at com.zhan_dui.download.DownloadRunnable.run(DownloadRunnable.java:101)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  17 has been succeesfully finished!
  CurrentPosition:0 EndPosition:-1Rmaining:-1 com.zhan_dui.download.DownloadRunnable@7bd3e136 can not be splited ,less than 1M
  java.net.ConnectException: Connection timed out: connect
  19 has been succeesfully finished!
  at java.net.DualStackPlainSocketImpl.connect0(Native Method)
  at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  at java.net.Socket.connect(Socket.java:589)
  at java.net.Socket.connect(Socket.java:538)
  at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
  at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
  at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
  at sun.net.www.http.HttpClient.New(HttpClient.java:308)
  at sun.net.www.http.HttpClient.New(HttpClient.java:326)
  at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
  at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
  at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
  at com.zhan_dui.download.DownloadRunnable.run(DownloadRunnable.java:101)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
  Download Task ID:21 has been started! Range From 0 To 2102879
  Download Task ID:22 has been started! Range From 2102880 To 4205759
  Download Task ID:23 has been started! Range From 4205760 To 6308639
  Download Task ID:24 has been started! Range From 6308640 To 8411520
  javax.xml.bind.UnmarshalException
- with linked exception:
  [org.xml.sax.SAXParseException; systemId: file:/E:/opensource/github/java-multithread-downloader/files/test1.tmp; lineNumber: 1; columnNumber: 1; 文件提前结束。]
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162)
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171)
  at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:189)
  at com.zhan_dui.download.DownloadMission.resumeMission(DownloadMission.java:312)
  at com.zhan_dui.download.DownloadMission.startMission(DownloadMission.java:339)
  at com.zhan_dui.download.DownloadManager.start(DownloadManager.java:64)
  at com.zhan_dui.download.Test.main(Test.java:29)
  Caused by: org.xml.sax.SAXParseException; systemId: file:/E:/opensource/github/java-multithread-downloader/files/test1.tmp; lineNumber: 1; columnNumber: 1; 文件提前结束。
  at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
  at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
  at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
  at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
  at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1438)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1019)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
  at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
  at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
  at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
  at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
  at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
  at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
  at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
  ... 9 more
  Downloader information Speed:0/S Down Size:166 B
  Download Task ID:26 has been started! Range From 13670950 To 27341899
  Download Task ID:18 has been started! Range From 27341900 To 41012849
  Download Task ID:20 has been started! Range From 41012850 To 54683800
  Download Task ID:25 has been started! Range From 0 To 13670949
  22 has been succeesfully finished!
  CurrentPosition:13670950 EndPosition:27341899Rmaining:13670949  Center position:20506424Download Task ID:22 has been started! Range From 20506425 To 27341899
  24 has been succeesfully finished!
  CurrentPosition:20506425 EndPosition:27341899Rmaining:6835474  Center position:2392416221 has been succeesfully finished!
  CurrentPosition:20506425 EndPosition:23924162Rmaining:3417737  Center position:22215293Download Task ID:19 has been started! Range From 23924163 To 27341899
  23 has been succeesfully finished!
  CurrentPosition:20506425 EndPosition:22215293Rmaining:1708868 com.zhan_dui.download.DownloadRunnable@66bef703 can not be splited ,less than 1M
  Download Task ID:17 has been started! Range From 22215294 To 23924162
  CurrentPosition:13670950 EndPosition:20506424Rmaining:6835474  Center position:17088687Download Task ID:21 has been started! Range From 17088688 To 20506424
  26 has been succeesfully finished!
  CurrentPosition:20506591 EndPosition:22215293Rmaining:1708702 com.zhan_dui.download.DownloadRunnable@66bef703 can not be splited ,less than 1M
  CurrentPosition:166 EndPosition:13670949Rmaining:13670783  Center position:6835557Download Task ID:26 has been started! Range From 6835558 To 13670949
  17 has been succeesfully finished!
  CurrentPosition:20506591 EndPosition:22215293Rmaining:1708702 com.zhan_dui.download.DownloadRunnable@66bef703 can not be splited ,less than 1M
  CurrentPosition:166 EndPosition:6835557Rmaining:6835391  Center position:3417861Download Task ID:17 has been started! Range From 3417862 To 6835557
  Downloader information Speed:1.8 KB/S Down Size:1.8 KB
  25 has been succeesfully finished!
  CurrentPosition:20506591 EndPosition:22215293Rmaining:1708702 com.zhan_dui.download.DownloadRunnable@66bef703 can not be splited ,less than 1M
  CurrentPosition:23924329 EndPosition:27341899Rmaining:3417570  Center position:25633114Download Task ID:25 has been started! Range From 25633115 To 27341899
  21 has been succeesfully finished!
  CurrentPosition:20506591 EndPosition:22215293Rmaining:1708702 com.zhan_dui.download.DownloadRunnable@66bef703 can not be splited ,less than 1M
  CurrentPosition:25633115 EndPosition:27341899Rmaining:1708784 com.zhan_dui.download.DownloadRunnable@64f18374 can not be splited ,less than 1M
  CurrentPosition:23924329 EndPosition:25633114Rmaining:1708785 com.zhan_dui.download.DownloadRunnable@60ce1b32 can not be splited ,less than 1M
  CurrentPosition:27342066 EndPosition:41012849Rmaining:13670783  Center position:34177457Download Task ID:21 has been started! Range From 34177458 To 41012849
  22 has been succeesfully finished!
  19 has been succeesfully finished!
  CurrentPosition:34177458 EndPosition:41012849Rmaining:6835391 CurrentPosition:34177458 EndPosition:41012849Rmaining:6835391  Center position:37595153 Center position:37595153Download Task ID:22 has been started! Range From 37595154 To 41012849
  Download Task ID:19 has been started! Range From 37595154 To 41012849
  18 has been succeesfully finished!
  CurrentPosition:34177458 EndPosition:37595153Rmaining:3417695  Center position:3588630520 has been succeesfully finished!
  CurrentPosition:34177458 EndPosition:35886305Rmaining:1708847 Download Task ID:24 has been started! Range From 35886306 To 37595153
  26 has been succeesfully finished!
  CurrentPosition:34177458 EndPosition:35886305Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@5eb46450 can not be splited ,less than 1M
  CurrentPosition:37595154 EndPosition:41012849Rmaining:3417695  Center position:3930400117 has been succeesfully finished!
  CurrentPosition:34177458 EndPosition:35886305Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@5eb46450 can not be splited ,less than 1M
  CurrentPosition:37595154 EndPosition:39304001Rmaining:1708847 25 has been succeesfully finished!
  CurrentPosition:34177458 EndPosition:35886305Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@5eb46450 can not be splited ,less than 1M
  CurrentPosition:37595154 EndPosition:39304001Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@5eb46450 can not be splited ,less than 1M
  CurrentPosition:37595154 EndPosition:39304001Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@6982e9cd can not be splited ,less than 1M
  CurrentPosition:37595154 EndPosition:41012849Rmaining:3417695  Center position:39304001Download Task ID:23 has been started! Range From 39304002 To 41012849
  com.zhan_dui.download.DownloadRunnable@6982e9cd can not be splited ,less than 1M
  Download Task ID:18 has been started! Range From 39304002 To 41012849
  CurrentPosition:37595154 EndPosition:39304001Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@6982e9cd can not be splited ,less than 1M
  CurrentPosition:37595154 EndPosition:39304001Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@3fffefba can not be splited ,less than 1M
  CurrentPosition:39304002 EndPosition:41012849Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@3fffefba can not be splited ,less than 1M
  com.zhan_dui.download.DownloadRunnable@8cfdc94 can not be splited ,less than 1M
  CurrentPosition:39304002 EndPosition:41012849Rmaining:1708847 CurrentPosition:39304002 EndPosition:41012849Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@8cfdc94 can not be splited ,less than 1M
  com.zhan_dui.download.DownloadRunnable@cf05955 can not be splited ,less than 1M
  CurrentPosition:39304002 EndPosition:41012849Rmaining:1708847 CurrentPosition:35886306 EndPosition:37595153Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@49f2d6af can not be splited ,less than 1M
  com.zhan_dui.download.DownloadRunnable@cf05955 can not be splited ,less than 1M
  CurrentPosition:35886306 EndPosition:37595153Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@49f2d6af can not be splited ,less than 1M
  21 has been succeesfully finished!
  CurrentPosition:37595154 EndPosition:39304001Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@6982e9cd can not be splited ,less than 1M
  CurrentPosition:37595154 EndPosition:39304001Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@3fffefba can not be splited ,less than 1M
  CurrentPosition:39304002 EndPosition:41012849Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@8cfdc94 can not be splited ,less than 1M
  CurrentPosition:39304002 EndPosition:41012849Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@cf05955 can not be splited ,less than 1M
  CurrentPosition:35886306 EndPosition:37595153Rmaining:1708847 com.zhan_dui.download.DownloadRunnable@49f2d6af can not be splited ,less than 1M
  22 has been succeesfully finished!
  19 has been succeesfully finished!
  CurrentPosition:39304168 EndPosition:41012849Rmaining:1708681 18 has been succeesfully finished!
  23 has been succeesfully finished!
  24 has been succeesfully finished!
  CurrentPosition:35886472 EndPosition:37595153Rmaining:1708681 com.zhan_dui.download.DownloadRunnable@49f2d6af can not be splited ,less than 1M
  com.zhan_dui.download.DownloadRunnable@cf05955 can not be splited ,less than 1M
  Downloader information Speed:1.6 KB/S Down Size:3.4 KB
  Downloader information Speed:0/S Down Size:3.4 KB
  Downloader information Speed:0/S Down Size:3.4 KB
  Downloader information Speed:0/S Down Size:3.4 KB
  Downloader information Speed:0/S Down Size:3.4 KB
  .....

**Comment by shuaiqingli** [comment]
运行环境 jdk 1.8.0_91  window7 64bit
运行 Test.java 报错
